[pytest]
testpaths     = tests
python_files  = test_*.py
python_classes= Test*
python_functions = test_*
addopts       = -v --tb=short --color=yes

# Bỏ qua warning không quan trọng
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning:tensorflow
